theme: jekyll-theme-cayman
title: Workshop on Robot Skill Transfer from Simulation to Real World Deployment in Manufacturing Industries and Warehouses
description: TransLearn Workshop at IEEE RO-MAN 2019 - Le Meridien, New Delhi, India - Room R2 (Sovereign 2) - October 17, 2019
